const mongoose = require("mongoose");
const db = require("../models");
mongoose.Promise = global.Promise;

// This file empties the Users collection and inserts the users below

mongoose.connect(
  process.env.MONGODB_URI || "mongodb://localhost/datecreate"
);

const DateCreateUserSeed = [
  {
    screenName: "lcrouch",
    firstName: "Levi",
    lastName: "Crouch",
    age: 41,
    gender: "M",
    locCity: "San Diego",
    locState: "CA",
    bioGaming: ["Unreal Tournament", "Risk"],
    bioTechnology: ["JavaScript", "Powershell"],
    bioAFKHobbies: ["Hiking", "Woodworking", "Working on Cars"], 
    bioMovies: ["The Shawshank Redemption", "Planes, Trains, and Automobiles", "The Princess Bride"],
    bioTV: ["Narcos", "Family Guy", "Peaky Blinders"],
    bioMusic: ["Pop", "Metal", "Classic Country", "Rap", "Motown"],
    bioCurrentlyListening: ["2pac"],
    bioCurrentlyReading: ["Till Death us do part"],
    bioCurrentlyWatching: ["Peaky Blinders S3", "Comedians in Cars Getting Coffee"],
    bioMantra: "I need an adult",
    bioCurrentRelStatus: true,
    savedPotentials: [],
    contactList: [],
    reqGender: "F",
    reqTech: [],
    reqGaming: [],
    reqLocCity: "San Diego",
    reqLocState: "CA",
    reqAgeMin: 35,
    reqAgeMax: 45,
    reqAFKHobbies: "Hiking",
    privBlockedUserIds: []
  },
  {
    screenName: "tthompson",
    firstName: "Travis",
    lastName: "Thompson",
    age: 31,
    gender: "M",
    locCity: "San Diego",
    locState: "CA",
    bioGaming: ["PUBG"],
    bioTechnology: ["JavaScript"],
    bioAFKHobbies: ["Hiking"], 
    bioMovies: [],
    bioTV: [],
    bioMusic: [],
    bioCurrentlyListening: [],
    bioCurrentlyReading: [],
    bioCurrentlyWatching: ["Game of Thrones"],
    bioMantra: "",
    bioCurrentRelStatus: true,
    savedPotentials: [],
    contactList: [],
    reqGender: "F",
    reqTech: [],
    reqGaming: [],
    reqLocCity: "San Diego",
    reqLocState: "CA",
    reqAgeMin: 25,
    reqAgeMax: 35,
    reqAFKHobbies: "Hiking",
    privBlockedUserIds: []
  },
  {
    screenName: "ChickenKiller",
    firstName: "Peter",
    lastName: "Griffin",
    age: 45,
    gender: "M",
    locCity: "Quahog",
    locState: "RI",
    bioGaming: [""],
    bioTechnology: ["Internet"],
    bioAFKHobbies: ["Crazy adventures with my bro's"],
    bioMovies: ["Roadhouse"],
    bioTV: ["The Simpsons", "The Cleveland Show", "Family Guy", "American Dad"],
    bioMusic: ["Pop"],
    bioCurrentlyListening: ["Surfin' Bird"],
    bioCurrentlyReading: ["TV Guide"],
    bioCurrentlyWatching: "Gumbel & Gumbel",
    bioMantra: "When you poop in your dreams, you poop in real life",
    bioCurrentRelStatus: false,
    savedPotentials: [],
    contactList: [],
    reqGender: "F",
    reqTech: [],
    reqGaming: [],
    reqLocCity: "Quahog",
    reqLocState: "RI",
    reqAgeMin: 18,
    reqAgeMax: 99,
    reqAFKHobbies: [],
    privBlockedUserIds: []
  },
  {
    screenName: "lgriffin",
    firstName: "Lois",
    lastName: "Griffin",
    age: 43,
    gender: "F",
    locCity: "Quahog",
    locState: "RI",
    bioGaming: [],
    bioTechnology: [],
    bioAFKHobbies: ["Taking care of my babies", "Stealing"], 
    bioMovies: [],
    bioTV: ["The Simpsons", "The Cleveland Show", "Family Guy", "American Dad"],
    bioMusic: ["Pop"],
    bioCurrentlyListening: ["Surfin' Bird"],
    bioCurrentlyReading: [],
    bioCurrentlyWatching: [],
    bioMantra: "Oh Peter!",
    bioCurrentRelStatus: false,
    savedPotentials: [],
    contactList: [],
    reqGender: "M",
    reqTech: [],
    reqGaming: [],
    reqLocCity: "Quahog",
    reqLocState: "RI",
    reqAgeMin: 35,
    reqAgeMax: 50,
    reqAFKHobbies: [],
    privBlockedUserIds: []
  },
  {
    screenName: "homerjaysimpson",
    firstName: "Homer",
    lastName: "Simpson",
    age: 45,
    gender: "M",
    locCity: "Springfield",
    locState: "MO",
    bioGaming: [""],
    bioTechnology: ["Nuclear"],
    bioAFKHobbies: ["Hanging out at Moe's"],
    bioMovies: ["The Simpsons Movie"],
    bioTV: ["Family Guy", "Krusty the Klown Show"],
    bioMusic: ["Jazz"],
    bioCurrentlyListening: ["Bleedin' Gums Murphy"],
    bioCurrentlyReading: ["TV Guide"],
    bioCurrentlyWatching: "Krusty the Klown Show",
    bioMantra: "D'oh!",
    bioCurrentRelStatus: false,
    savedPotentials: [],
    contactList: [],
    reqGender: "F",
    reqTech: [],
    reqGaming: [],
    reqLocCity: "Springfield",
    reqLocState: "MO",
    reqAgeMin: 18,
    reqAgeMax: 99,
    reqAFKHobbies: [],
    privBlockedUserIds: []
  },
  {
    screenName: "msimpson",
    firstName: "Marge",
    lastName: "Simpson",
    age: 43,
    gender: "F",
    locCity: "Springfield",
    locState: "MO",
    bioGaming: [],
    bioTechnology: [],
    bioAFKHobbies: ["Taking care of my babies"], 
    bioMovies: [],
    bioTV: ["Family Guy", "Krusty the Klown Show"],
    bioMusic: ["Jazz"],
    bioCurrentlyListening: ["Bleedin' Gums Murphy"],
    bioCurrentlyReading: [],
    bioCurrentlyWatching: [],
    bioMantra: "Oh Homie!",
    bioCurrentRelStatus: false,
    savedPotentials: [],
    contactList: [],
    reqGender: "M",
    reqTech: [],
    reqGaming: [],
    reqLocCity: "Springfield",
    reqLocState: "MO",
    reqAgeMin: 35,
    reqAgeMax: 50,
    reqAFKHobbies: [],
    privBlockedUserIds: []
  },
  {
    screenName: "mpritchett",
    firstName: "Mitch",
    lastName: "Pritchett",
    age: 38,
    gender: "M",
    locCity: "Los Angeles",
    locState: "CA",
    bioGaming: [],
    bioTechnology: [],
    bioAFKHobbies: ["Musical Theatre", "Ice Skating"], 
    bioMovies: [],
    bioTV: ["Modern Family"],
    bioMusic: ["Show Tunes"],
    bioCurrentlyListening: ["Les Miserables"],
    bioCurrentlyReading: [],
    bioCurrentlyWatching: [],
    bioMantra: "I know I’m not the handiest guy, but I’m still a man and I want to be able to look out into my yard and say, ‘There’s a little bit of me in that princess castle.",
    bioCurrentRelStatus: false,
    savedPotentials: [],
    contactList: [],
    reqGender: "M",
    reqTech: [],
    reqGaming: [],
    reqLocCity: "Los Angeles",
    reqLocState: "CA",
    reqAgeMin: 35,
    reqAgeMax: 50,
    reqAFKHobbies: [],
    privBlockedUserIds: []
  },
  {
    screenName: "camtucker",
    firstName: "Cameron",
    lastName: "Tucker",
    age: 39,
    gender: "M",
    locCity: "Los Angeles",
    locState: "CA",
    bioGaming: [],
    bioTechnology: [],
    bioAFKHobbies: ["Musical Theatre", "Fighting Illini"], 
    bioMovies: [],
    bioTV: ["Modern Family"],
    bioMusic: ["Country"],
    bioCurrentlyListening: ["Garth Brooks"],
    bioCurrentlyReading: [],
    bioCurrentlyWatching: [],
    bioMantra: "I’m sort of like Costco. I’m big, I’m not fancy and I dare you to not like me.",
    bioCurrentRelStatus: false,
    savedPotentials: [],
    contactList: [],
    reqGender: "M",
    reqTech: [],
    reqGaming: [],
    reqLocCity: "Los Angeles",
    reqLocState: "CA",
    reqAgeMin: 35,
    reqAgeMax: 50,
    reqAFKHobbies: [],
    privBlockedUserIds: []
  }
];

db.DateCreateUser
  .remove({})
  .then(() => db.DateCreateUser.collection.insertMany(DateCreateUserSeed))
  .then(data => {
    console.log(data.insertedIds.length + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
